version: "2"
services:
  app:
    container_name: app-a2
    build:
      context: ../
      dockerfile: deployments/Dockerfile
    env_file:
      - dockers.env
    links:
      - db:db
    depends_on:
      - db
    ports:
      - "10082:10082"
    networks:
      - a2_net
    restart: unless-stopped

  db:
    container_name: db-a2
    image: mysql:5.7
    ports:
      - "3307:3307"
    env_file:
      - dockers.env
    networks:
      - a2_net
    volumes:
      - storage-a2-database:/var/lib/mysql
      - ../db:/docker-entrypoint-initdb.d

volumes:
  storage-a2-database:

networks:
  a2_net:
