version: '3'

networks:
    insecure_net:

volumes:
    mongo_vol:

services:
    api:
        container_name: a3_api
        build: 
            context: ../
            dockerfile: deployments/api.Dockerfile
        ports: 
            - "9999:9999"
        networks: 
            - insecure_net
        command: "go run main.go"
        depends_on:
            - mongodb
        external_links:
            - mongodb:mongodb
        environment:
            - MONGO_DB_NAME=${MONGO_DB_NAME}
            - MONGO_HOST=${MONGO_HOST}
            - MONGO_USER=${MONGO_USER}
            - MONGO_PASSWORD=${MONGO_PASSWORD}

    mongodb:
        container_name: mongodb
        build:
            context: ../
            dockerfile: deployments/mongo.Dockerfile
        ports:
          - "27017:27017"
          - "27018:27018"
        volumes:
            - mongo_vol:/data/db
        networks:
            - insecure_net
        environment:
            - MONGO_DB_NAME=${MONGO_DB_NAME}
            - MONGO_HOST=${MONGO_HOST}
            - MONGO_USER=${MONGO_USER}
            - MONGO_PASSWORD=${MONGO_PASSWORD}
